[package]
name = "firebase_admin"
version = "0.1.0"
authors = ["Duncan Dean <duncangleeddean@gmail.com>"]
edition = "2018"
exclude = ["examples/*", "tests/*"]

[dependencies]
reqwest = "0.9.5"
lazy_static = "1.2.0"
futures = "0.1"
